'use client'

import { useTransition } from 'react'
import { WeeklyCalendar } from '@/components/calendar/WeeklyCalendar'
import type { ActionResult } from '@/lib/action-result'

type EventWithRels = {
  id: string
  title: string
  date: Date | string
  type: string
  companyId: string
  userId: string
  autoGenerated: boolean
  relatedId: string | null
  propertyId: string | null
  unitId: string | null
  createdAt: Date
  user: { id: string; name: string }
  property: { id: string; name: string } | null
  unit: { id: string; unitNumber: string } | null
}

type Props = {
  events: EventWithRels[]
  deleteAction: (id: string) => Promise<ActionResult<void>>
}

export function CalendarClient({ events, deleteAction }: Props) {
  const [, startTransition] = useTransition()

  async function handleDelete(id: string) {
    startTransition(async () => {
      await deleteAction(id)
    })
  }

  return <WeeklyCalendar events={events} onDelete={handleDelete} />
}
